### ISSUE TITLE
mnist_dataset

### ISSUE THREAD

**Issue by Amri95** [Bao-Jiarong/SqueezeNet-SqueezeNetv2-SqueezeNetv3-Implementation#1]
hello there... could you please provide me the mnist data format you used in the squeezeNet model?amritaranamagar60@gmail.com

Thankyou

**Comment by Bao-Jiarong** [comment]
Actually I extracted the images from the following official link: 
[mnist dataset](http://yann.lecun.com/exdb/mnist/)
you can use the following code for extracting the images:
[how to extract](https://gist.github.com/ceykmc/c6f3d27bb0b406e91c27)
